version: '3.8'

services:
  redis-cache:
    build:
      context: .
    ports:
      - "7171:7171"
    restart: unless-stopped
    environment:
      - TZ=UTC
    deploy:
      resources:
        limits:
          memory: 1G

